### ISSUE TITLE
make run-tests does not work

### ISSUE THREAD

**Issue by lem0n4id** [layer5io/discuss-twitter#8]
#### Description
`make run-tests` gives me the following output

```bash
Lemon@DESKTOP-LEMON MINGW64 /f/codes/python-container-action/discuss-twitter (feature/lem0n4id/issue#4)
$ make run-tests
make: *** No rule to make target 'run-tests'.  Stop.
```

#### Expected Behavior
I'm not sure since this is my first time using make

#### Environment:
- Host OS: windows 10

**Comment by lem0n4id** [comment]
I found it in the [contributing.md here](https://github.com/layer5io/discuss-twitter/blob/master/CONTRIBUTING.md#tests)

**Comment by warunicorn19** [comment]
@lem0n4id i think it's some mistake in the contributing guide since i dont see any such command in the Makefile, that's the reason it's not working.
